Allow the user to choose which type of clients to instrument and allow advanced configuration.
honeycombio/honeycomb-opentelemetry-dotnet pull request #129
Opened 2021-10-21 21:44 UTC by ericsampson

Allow the user to choose which type of clients to instrument and allow advanced configuration of them.
Follow Microsoft's recommended method of implementing the AddFooService pattern by using an Action delegate as the way to configure the services. This is a breaking change, but is a quick refactor for users and this is still a beta package so I think it should be ok?

I didn't update the changelog yet until this PR has been reviewed.

Thanks!

2021-11-04 12:19 UTC, MikeGoldsmith requested changes
Hey @ericsampson - sorry for the delay in getting back to you.

This looks great, thank you for the time you've put into it. I've left feedback but is mainly just comments, whitespace, etc.

Thank you!

2021-11-04 12:19 UTC, MikeGoldsmith commented on examples/netcoreapp2.1/netcoreapp2.1.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
Accidental downgrade?

2021-11-04 12:19 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        /// optional Options for HttpClient instrumentation.
```suggestion
        /// (Optional) Options delegate to configure HttpClient instrumentation.

```

2021-11-04 12:19 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        /// optional Options for SqlClient instrumentation.
```suggestion
        /// (Optional) Options delegate to configure SqlClient instrumentation.
```

2021-11-04 12:19 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        /// optionl Options for StackExchance.Redis instrumentation.
```suggestion
        /// (Optional) Options delegate to configure StackExchance.Redis instrumentation.

```

2021-11-04 12:19 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
> +
nit: unneeded whitespace
```suggestion
```

2021-11-04 12:19 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
> +         /// <summary>
```suggestion
        /// <summary>
```

2021-11-04 12:19 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
> +        /// Configures the <see cref="TracerProviderBuilder"/> to send telemetry data to Honeycomb
```suggestion
        /// Configures the <see cref="TracerProviderBuilder"/> to send telemetry data to Honeycomb.

```

2021-11-04 12:19 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
> +
```suggestion
            if (options.InstrumentGprcClient && options.InstrumentHttpClient) // HttpClient needs to be instrumented for GrpcClient instrumentation to work.
            {
                // See https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.GrpcNetClient/README.md#suppressdownstreaminstrumentation
                builder.AddGrpcClientInstrumentation(options => options.SuppressDownstreamInstrumentation = true);
            }
```

2021-11-05 04:30 UTC, ericsampson commented on examples/netcoreapp2.1/netcoreapp2.1.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
it wasn't accidental, the original 2.2.0 was giving me the following. Do you not get this error?
```
Error: Detected package version outside of dependency constraint: Microsoft.AspNetCore.App 2.1.1 requires Microsoft.AspNetCore.Razor.Design (>= 2.1.1 && < 2.2.0) but version Microsoft.AspNetCore.Razor.Design 2.2.0 was resolved.
```

2021-11-05 04:31 UTC, ericsampson commented
@MikeGoldsmith don't mention it, you've got way more important things going on! Thanks for catching my sloppy formatting :)
I left a comment about that Razor dependency, see what you think. Cheers

2021-11-05 17:12 UTC, MikeGoldsmith commented on examples/netcoreapp2.1/netcoreapp2.1.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
I hadn't seen it, but as it's an example, I'm okay with it being updated 👍🏻

2021-11-05 17:12 UTC, MikeGoldsmith approved these changes
Great, thank you @ericsampson  👍🏻

2021-11-05 17:12 UTC, merged

2021-11-05 18:04 UTC, cartermp commented
🎉