Vera.optional key dataset
honeycombio/honeycomb-opentelemetry-dotnet pull request #161
Opened 2021-12-06 21:00 UTC by vreynolds

## Which problem is this PR solving?

- allow using the distro with a collector, where API key and dataset is configured in the collector config
- closes #160 

## Short description of the changes

- most of the diff is formatting, if there's any unfavorable changes LMK and I will update editorconfig
- write a warning to the console when API key or dataset is not configured, don't configure OTLP exporter headers if they're missing
- NOTE: in my testing, the previous `ArgumentException` was swallowed, so it would just silently not configure the exporter

2021-12-07 14:51 UTC, MikeGoldsmith requested changes
Looks good 👍🏻 

Your IDE is super finicky about formatting 😁

2021-12-07 14:51 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
> +                        if (!string.IsNullOrWhiteSpace(options.MetricsApiKey))
I think we should validate `options.MetricsDataset` is also not empty before setting the header like we do in TracerProviderBuilder.

2021-12-07 14:51 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private static readonly string SDefaultServiceVersion = "{unknown_service_version}";
I think should use `private const string` instead of `private static readonly string` here.

2021-12-07 14:51 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private static Dictionary<string, string> _commandLineSwitchMap = new Dictionary<string, string>
This could be `private static readonly` as it's only set during app start up.

2021-12-07 17:36 UTC, vreynolds commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private static readonly string SDefaultServiceVersion = "{unknown_service_version}";
Looks like we reassign them below with assembly info, so they can't be const

2021-12-07 17:38 UTC, vreynolds commented on src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
> +                        if (!string.IsNullOrWhiteSpace(options.MetricsApiKey))
Will add for completion, though it's technically redundant since we're already in that `if` block

2021-12-08 09:07 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
> +                        if (!string.IsNullOrWhiteSpace(options.MetricsApiKey))
Ah, yeah - you're right. We didn't need to check twice 👍🏻

2021-12-08 09:08 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private static readonly string SDefaultServiceVersion = "{unknown_service_version}";
I think these should be const values, and ServiceName & ServiceVersion should use them. Not a big deal, we can fix it another time.

2021-12-08 09:08 UTC, MikeGoldsmith approved these changes

2021-12-08 16:04 UTC, merged