Added Console Trace link writer
honeycombio/honeycomb-opentelemetry-dotnet pull request #222
Opened 2022-07-23 11:06 UTC by martinjt

Adds a link exporter that writes all root spans to the console with a link to honeycomb for viewing it.

2022-07-25 10:24 UTC, MikeGoldsmith requested changes
Thanks for the contribution 👍🏻 

I like what you've done and I think it's heading in the right direction. I've left some comments to make use of existing Options values and suggested some other things.

I've focused on external config & behaviour as internals can be updated later and this is likely a debug tool rather than being activated in production systems.

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +    /// Writes links to the Honeycomb for all root spans
```suggestion
    /// Writes links to the Console for all root spans

```

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +        private readonly HoneycombOptions _options;
We only need the service name outside of init, let's capture that instead directly instead of keeping a reference to the whole options object.

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +        private string _teamSlug;
I think getting the team and environment slugs could be reusable so may end up being passed in instead of being resolved inside this span processor.

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +            }
We can use _options.TracesEndpoint instead of hardcoding.

```suggestion
            var httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri(_options.TracesEndpoint);
            httpClient.DefaultRequestHeaders.Add("X-Honeycomb-Team", _options.ApiKey);

            var response = httpClient.GetAsync("1/auth").GetAwaiter().GetResult();
            if (!response.IsSuccessStatusCode) {
                Console.WriteLine("Didn't get a valid response from Honeycomb");
                return;
            }
```

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +            if (string.IsNullOrEmpty(_environmentSlug) ||
We can generate trace links for classic datasets, it just needs to omit the environment segments.

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +                    Console.WriteLine($"TraceLink: {GetTraceLink(activity.TraceId.ToString())}");
I think it would be nice to combine these into a single line for easier searching and reduce screen congestion for higher volume apps.

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +            return $"http://ui.honeycomb.io/{_teamSlug}/environments/{_environmentSlug}/datasets/{dataset}/trace?trace_id={traceId}";
Same as above, we should consider allowing trace links to be created for classic (non-env) based users too.

```suggestion
            return $"{_options.TracesEndpoint}/{_teamSlug}/environments/{_environmentSlug}/datasets/{dataset}/trace?trace_id={traceId}";

```

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +                    Console.WriteLine($"Trace Emitted for {activity.DisplayName}");
Would be nice to expand this in the future to write to an `ILogger` instead of directly to console. Then users can select where they want these to appear.

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/EnvironmentOptions.cs
> +        private const string WriteTraceLinksToConsoleKey = "WRITE_TRACE_LINKS_TO_CONSOLE";
This feels long, maybe `LOG_TRACE_LINKS`. If we do go along the route of using an ILogger in the future, these trace links may go elsewhere.

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        public bool WriteTraceLinksToConsole
Should match env var above.

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        { get; set; }
Was this intentional, or did your IDE move this?

2022-07-25 10:24 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +            { "--honeycomb-write-trace-links-to-console", "writetracelinkstoconsole" },
Should match env var

2022-07-25 18:16 UTC, martinjt reviewed
Fixed feedback

2022-07-25 18:16 UTC, martinjt commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +            }
Given that someone can override the traces endpoint, is that an issue? My worry would be people overriding that, and not having the auth API... maybe I'm being a little over cautious?

2022-07-25 18:16 UTC, martinjt commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +            if (string.IsNullOrEmpty(_environmentSlug) ||
How would we detect if it's a classic dataset?

2022-07-25 18:16 UTC, martinjt commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +                    Console.WriteLine($"Trace Emitted for {activity.DisplayName}");
I actually don't want it going through the logging framework, as that could take it into other pipelines, and this is specifically for local development.

2022-07-25 18:16 UTC, martinjt commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +                    Console.WriteLine($"TraceLink: {GetTraceLink(activity.TraceId.ToString())}");
Keep in mind that this is just for the root span, not all spans, so even in large volume applications, we should only see a small amount of spans.

1 line is actually pretty long as the url is already quite long, which is why I extended it to 2. Happy to hear thoughts though, I'm not 100% convinced this is right.

2022-07-25 18:16 UTC, martinjt commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +            return $"http://ui.honeycomb.io/{_teamSlug}/environments/{_environmentSlug}/datasets/{dataset}/trace?trace_id={traceId}";
If I have a way of knowing that it's a classic just from the ApiKey or settings, then I'm happy to add it.

2022-07-25 18:27 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/ConsoleLinksExporter.cs
> +            if (string.IsNullOrEmpty(_environmentSlug) ||
> How would we detect if it's a classic dataset?

Classic (nee Legacy) API key is 32 characters:

https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/5317498f5484f6031e4c5f675894f5c37b0dabc6/src/Honeycomb.OpenTelemetry/HoneycombOptions.cs#L56

2022-07-25 18:57 UTC, vreynolds commented on src/Honeycomb.OpenTelemetry/EnvironmentOptions.cs
> +        private const string WriteTraceLinksToConsoleKey = "WRITE_TRACE_LINKS_TO_CONSOLE";
in zoom convo, we thought `ENABLE_LOCAL_VISUALIZATIONS' would work nicely, as a more generic "mode" setting that is not too specific with what we're writing where

2022-07-26 11:21 UTC, MikeGoldsmith approved these changes
This looks good - thanks @martinjt 👍🏻 

I'm happy with the changes to external API (env var / settings.json) and what it outputs. The remainder is internal logic and can be iterated on as we wish.

2022-07-28 17:43 UTC, vreynolds commented
Circle is being weird, but I triggered the run by creating another branch off this PR.

There's an error trying to run tests:
`C:\Program Files\dotnet\sdk\5.0.406\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [C:\Users\circleci\project\test\Honeycomb.OpenTelemetry.Tests\Honeycomb.OpenTelemetry.Tests.csproj]`

2022-07-28 17:54 UTC, vreynolds commented
Looks like Circle may [not have .NET 6 in their orb](https://discuss.circleci.com/t/cant-see-to-find-an-orb-with-support-for-dotnet-6/42652/6)

2022-07-28 18:10 UTC, cartermp commented
STILL?! ugh

2022-07-28 21:28 UTC, martinjt commented
That's my bad... I didn't mean to upgrade the projects to .NET 6.  I'll
revert

On Thu, 28 Jul 2022, 19:10 Phillip Carter, ***@***.***> wrote:

> STILL?! ugh
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/pull/222#issuecomment-1198474346>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAM66AYSEZSRS563N2D3UIDVWLEJRANCNFSM54N2ZTTQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-07-28 21:54 UTC, cartermp commented
It's quite reasonable to do that, though. Blegh. It also means having a minimal apis example can't be done yet either. :shakes-fist-at-circle-ci:

2022-07-29 10:40 UTC, martinjt commented
I've added an install step to the CI build @cartermp , happy to revert to .NET 5 if we need to though.  I can't trigger the build, so let me know if it works.

2022-07-29 12:22 UTC, martinjt commented
Reverted this to .NET 5.0 as it was only the test project at this stage.

I'll investigate separately how we add .NET 6.0 inside the pipeline.

2022-08-01 13:42 UTC, MikeGoldsmith approved these changes

2022-08-01 13:42 UTC, merged