Add Redis instrumentation to example app
honeycombio/honeycomb-opentelemetry-dotnet pull request #242
Opened 2022-09-01 21:48 UTC by JamieDanielson

## Which problem is this PR solving?

- closes #106 

## Short description of the changes

- [x] uses local dependency
- [x] adds redis auto-instrumentation
- [ ] creates at least one manual span
- [x] has a curl-able endpoint

2022-09-07 11:59 UTC, MikeGoldsmith requested changes
Looks good. I've left feedback around the optional redis config options.

How about we say this example expects to use a local redis instance and leave all the redis config as enabled?

2022-09-07 11:59 UTC, MikeGoldsmith commented on examples/aspnetcore/Startup.cs
> +            ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(
I think this should be commented out too as we say the redis instrumentation is optional. This will try to connect even when Redis is not available.

2022-09-07 11:59 UTC, MikeGoldsmith commented on examples/aspnetcore/appsettings.json
> +    "InstrumentStackExchangeRedisClient": "true"
Same here, if redis instrumentation is optional, this should be commented out / set to false.

2022-09-08 17:46 UTC, JamieDanielson commented
> Looks good. I've left feedback around the optional redis config options.
> 
> How about we say this example expects to use a local redis instance and leave all the redis config as enabled?

I agree. I'm actually going to separate this into a new example app, so there is still a ready-made example that doesn't require redis.

2022-09-09 23:19 UTC, JamieDanielson commented on examples/aspnetcore/appsettings.json
> +    "InstrumentStackExchangeRedisClient": "true"
I've created a new app to show redis instrumentation to avoid the need for enabling/disabling, and left this one alone with just a bit of cleanup 👍

2022-09-09 23:20 UTC, JamieDanielson commented on examples/aspnetcore/Startup.cs
> +            ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(
I've created a new app to show redis instrumentation to avoid the need for enabling/disabling, and left this one alone with just a bit of cleanup 👍

2022-09-10 10:54 UTC, martinjt commented on examples/aspnetcore-redis/Startup.cs
> +            Console.WriteLine("we'll be running on https://localhost:5001/WeatherForecast");
Not sure we need this, it's output from the commandline. If we do keep it, we should pull the actual values rather than hardcoding.

2022-09-10 10:54 UTC, martinjt commented on examples/aspnetcore/Controllers/WeatherForecastController.cs
> +
We should remove the changes in this file from the PR

2022-09-10 10:54 UTC, martinjt commented on examples/aspnetcore/README.md
> +- First, set your Honeycomb API key and a service name in the [appsettings.json](appsettings.json) configuration file.
we should be asking people to use `appsettings.development.json` rather than appsettings, then remove and exclude the development json file from the repo.

Might also be easier to get them to set the environment variable.

2022-09-10 10:54 UTC, martinjt commented on examples/aspnetcore/Startup.cs
> +            Console.WriteLine("we'll be running on https://localhost:5001/WeatherForecast");
Think this needs removing as it's hardcoded, and won't be the same for all users (specifically those hosting in IIS with VisualStudio.

2022-09-12 12:18 UTC, MikeGoldsmith approved these changes

2022-09-12 12:18 UTC, MikeGoldsmith commented on examples/aspnetcore/README.md
> +- First, set your Honeycomb API key and a service name in the [appsettings.json](appsettings.json) configuration file.
Generally I agree, but this is explicitly an example app and shouldn't be used as a true guide for how to build apps. For example, there are tools that inject values into appsettings.json at deploy time for a given environment (testing, staging, etc).

2022-09-13 14:53 UTC, JamieDanielson commented on examples/aspnetcore/Controllers/WeatherForecastController.cs
> +
Since this PR is specifically about updating and cleaning up the example apps, I'd like to keep this whitespace fix in this one 👍

2022-09-13 14:54 UTC, merged