WIP: dockerize example and prep for smoke tests
honeycombio/honeycomb-opentelemetry-dotnet pull request #243
Opened 2022-09-06 22:37 UTC by JamieDanielson

## Which problem is this PR solving?

- closes #232 

## Short description of the changes

-

2022-09-10 11:02 UTC, martinjt reviewed
We should revisit this in the next version of the otel base library is out as we should be able to add this as an automated unit test.

2022-09-12 12:03 UTC, MikeGoldsmith requested changes

2022-09-12 12:03 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
> +#if (NETSTANDARD2_0_OR_GREATER || NETCOREAPP3_1_OR_GREATER)
I think we could use [NET5_0_OR_GREATER](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#conditional-compilation) here - netcoreapp3.1 should be covered by netstandard 2.1 and it looks like we're trying to move to newer SDK / runtime targets.

2022-09-13 15:01 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
> +#if (NETSTANDARD2_0_OR_GREATER || NETCOREAPP3_1_OR_GREATER)
https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/pull/243/commits/8fbeaf8f801b3073d7736f4535ba4c763d51c41e

2022-09-13 15:02 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
> +    <TargetFrameworks>net5.0;netstandard2.1;netstandard2.0;net462;</TargetFrameworks>
If we do net6.0 in our TargetFrameworks instead of net5.0, aren't we effectively dropping support for net5.0? We may want to do that, just wanted to be sure. If I set it to net6.0, I cannot run my example app in net5.0.

2022-09-13 20:19 UTC, JamieDanielson commented on examples/aspnetcore/Dockerfile
> +ENV ASPNETCORE_ENVIRONMENT="development"
done!

2022-09-13 20:23 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
> +    <TargetFrameworks>net5.0;netstandard2.1;netstandard2.0;net462;</TargetFrameworks>
Targeting both doesn't seem to be possible. Will update the main description as well; since .NET5 is [out of support](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle) as of May of this year, we will stick with .NET6 which also matches upstream as you pointed out.

2022-09-13 20:51 UTC, JamieDanielson commented on examples/aspnetcore/.dockerignore
> +**/obj/
https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1005

> If you're building a Docker image, make sure the .dockerignore file ignores the bin and obj directories. For more information, see GitHub pull request [dotnet/docs #29530](https://github.com/dotnet/docs/pull/29530).

2022-09-13 20:52 UTC, JamieDanielson commented on .circleci/config.yml
> +  windows: circleci/windows@5.0.0
[orb v5.0.0 came out end of July, supports .NET6](https://circleci.com/developer/orbs/orb/circleci/windows#orb-source)

2022-09-13 20:53 UTC, cartermp commented on src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
> +    <TargetFrameworks>net5.0;netstandard2.1;netstandard2.0;net462;</TargetFrameworks>
> Interesting - my understanding was that libraries should target API definitions (eg netstandard2.0) and apps target runtimes (eg netcoreapp).

Not necessarily. Only if you're aiming to write code _without_ having to multi-target. That's indeed a goal for a lot of libraries, but that's not an option for many libraries and tools, and I think we might fall into that so long as we carry an ASP.NET dependency.

2022-09-13 20:53 UTC, JamieDanielson commented on Makefile
> +	cd smoke-tests && docker-compose up -d --build && docker-compose down --volumes
This just proves a successful spin-up and spin-down of docker containers. When actual tests are added we can remove the `docker-compose down` from the smoke target, and ensure it's added into the test itself. Without it here, the container will stay up until Circle times it out.

2022-09-13 20:59 UTC, cartermp commented on src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
> -    <TargetFrameworks>netstandard2.0;netstandard2.1;net462</TargetFrameworks>
Really my only concern here is targeting netstandard and then conditionally pulling in and registering dependencies in code that aren't compatible with .NET Standard. But that's also related to our desire to restructure/relayer packaging.

2022-09-14 10:26 UTC, MikeGoldsmith commented on test/Honeycomb.OpenTelemetry.Tests/Honeycomb.OpenTelemetry.Tests.csproj
> +     <TargetFrameworks>net6.0</TargetFrameworks>
```suggestion
    <TargetFrameworks>net6.0</TargetFrameworks>
```

2022-09-14 10:26 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
> +#if (NET6_0_OR_GREATER)
Should this be `NETSTANDARD2_0_OR_GREATER || NET6_0_OR_GREATER`?

I think anyone currently using the distro with a netstandard compatible app (eg netcoreapp3) that's not net6, will fail that check.

2022-09-14 14:20 UTC, cartermp commented on src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
> +#if (NET6_0_OR_GREATER)
I don't think that will work if we update latest packages. https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNetCore/1.0.0-rc9.6 now targets net6.0 and net7.0 directly and so `AddAspNetCoreInstrumentation` won't be available.

2022-09-14 15:32 UTC, MikeGoldsmith approved these changes

2022-09-14 15:37 UTC, cartermp approved these changes

2022-09-14 15:37 UTC, cartermp commented on .circleci/config.yml
> +  windows: circleci/windows@5.0.0
it's morbin' time

2022-09-14 23:22 UTC, merged