Attempt to match Java distro resources
honeycombio/honeycomb-opentelemetry-dotnet pull request #249
Opened 2022-09-14 22:00 UTC by cartermp

I think this gets us as close as we can with https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/issues/119 given the following constraints:

* Can't use the new .NET 6 APIs that give you much richer OS and runtime information
* Can't rely on upstream OTel, since they don't have these resources implemented in the SDK
* Can't rely on pre-defined values from upstream since [they aren't specified](https://github.com/open-telemetry/opentelemetry-dotnet/issues/1281)

That said, I think it's valuable to have _something_ rather than nothing.

2022-09-15 10:07 UTC, MikeGoldsmith requested changes
Other than checking we have the correct number of items in an array, looks good 👍🏻

2022-09-15 10:07 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/ResourceBuilderExtensions.cs
> +            var parts = frameworkDescription.Split(' ');
I think it's wise to test we have the correct number of parts or we risk a invalid index runtime exception.

2022-09-15 14:04 UTC, cartermp commented on src/Honeycomb.OpenTelemetry/ResourceBuilderExtensions.cs
> +            var parts = frameworkDescription.Split(' ');
Yeah, actually it's a bit more complicated than this because of .NET Core. So what we're really after is a rudimentary parser. I'll do that.

2022-09-16 11:39 UTC, MikeGoldsmith approved these changes

2022-09-16 11:39 UTC, merged