Prepare v1.0.0/0.24.0 releases
honeycombio/honeycomb-opentelemetry-dotnet pull request #273
Opened 2022-09-23 13:28 UTC by MikeGoldsmith

## Which problem is this PR solving?
Prepares the 1.0.0/0.24.0-beta releases.

Blocked on merging:
- #268 
- #270 
  - need to update version to 0.24.0 once merged

## Short description of the changes
- Updates main package version to 1.0.0 and prerelease packages to v0.24.0-beta
- Adds changelog entry

2022-09-23 14:47 UTC, cartermp commented
Hmm, let's hold off on this just yet. I think we should do a sweep of how we name things first, since we can't change those after 1.0.

2022-09-23 14:50 UTC, cartermp commented
Issue here: https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/issues/274

2022-09-29 16:50 UTC, pkanal requested changes
I think we're ready to release! 🎉 I left a comment about a couple of PRs to add to the Enhancements but other than that I think we're good to go.

2022-09-29 16:50 UTC, pkanal commented on CHANGELOG.md
> +- Add Honeycomb.OpenTelemetry.Autoinstrumentations #270 | [@cartermp](https://github.com/cartermp)
We need to add #279 & #284 here I think

2022-09-29 16:50 UTC, pkanal commented on CHANGELOG.md
> +- Add http/protobuf smoke tests (#263) | [@pkanal](https://github.com/pkanal)
Smoke tests are available now for http/protobuf & grpc and also for metrics

2022-09-30 13:34 UTC, pkanal approved these changes
🚀 🚀 🚀 🚀 🚀 🚀 🚀

2022-09-30 13:47 UTC, merged