Purvi/traces path http
honeycombio/honeycomb-opentelemetry-dotnet pull request #279
Opened 2022-09-26 19:01 UTC by pkanal

## Which problem is this PR solving?

-

## Short description of the changes

-

2022-09-27 21:15 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private const string OtelExporterOtlpProtcolHttp = "http/protobuf";
```suggestion
        private const string OtelExporterOtlpProtocolHttp = "http/protobuf";
```
suggest rename symbol (I don't know why my eyes notice these things)

2022-09-27 21:15 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private const string OtelExporterOtlpProtcolGrpc = "grpc";
```suggestion
        private const string OtelExporterOtlpProtocolGrpc = "grpc";
```
suggest rename symbol (I don't know why my eyes notice these things)

2022-09-27 21:15 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        internal static readonly string SDefaultServiceVersion = "{unknown_service_version}";
```suggestion
        internal static readonly string SDefaultServiceVersion = "unknown_service_version";
```
I know this wasn't changed in this PR, but I realized this shows up with the brackets which I don't think we want.

2022-09-27 21:17 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private const string OtelExporterOtlpProtcolHttp = "http/protobuf";
Hm... yes, sounds like a feature request ticket for a different PR, but here we probably then need to change the const to include proto, e.g. `OtelExporterOtlpProtocolHttpProto`, so the json addition could be `OtelExporterOtlpProtcolHttpJson`. Will need the same for Java, though there's no json support there yet.

2022-09-27 21:33 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private const string OtelExporterOtlpProtcolHttp = "http/protobuf";
Ooh, seeing there are some tests in here for /1/metrics. Most of the hard work is done on that front then, and this refactoring makes the whole thing work a lot smoother.

2022-09-28 14:06 UTC, MikeGoldsmith requested changes
This looks great, thanks @pkanal 🎉 

Adds some feedback and suggestions plus some nits about whitespace 😄

2022-09-28 14:06 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
> +            if (options is null)
This guard needs to be before the `ApplyEnvironmentOptions` call otherwise we'd get a null reference exception

2022-09-28 14:06 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
> +                throw new ArgumentNullException(nameof(options), "No Honeycomb options have been set in appsettings.json, environment variables, or the command line.");
We don't support command line args anymore 😄 
```suggestion
                throw new ArgumentNullException(nameof(options), "No Honeycomb options have been set in appsettings.json or environment variables.");
```

2022-09-28 14:06 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
> +
nit: remove whitespace
```suggestion
```

2022-09-28 14:06 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
>              if (options is null)
Guard needs to happen before call to `ApplyEnvironmentOptions`

2022-09-28 14:06 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
> +
nit: remove whitespace
```suggestion
```

2022-09-28 14:06 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
> +                Console.WriteLine(JsonSerializer.Serialize(options, new JsonSerializerOptions { WriteIndented = true }));
:tada:

2022-09-28 14:32 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +            return TracesEndpoint ?? endpoint.ToString();
If we do that, we may want to consider checking for this; if endpoint does not end in `v1/traces`, should we add it? According to upstream spec... we wouldn't touch the TracesEndpoint if explicitly set, and we would only append on the generic Endpoint.

Per our conversation: Let's check on generic Endpoint if provided - and append if needed, and leave TracesEndpoint alone.

2022-09-28 14:37 UTC, JamieDanielson commented on src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
> +            if (options is null)
Per our conversation, set to default options if none provided, and remove the error entirely:

```csharp
            if (options is null)
            {
                // set defaults, so we don't get the error block
            }
```

2022-09-28 15:04 UTC, pkanal commented on src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
> +        private const string OtelExporterOtlpProtcolHttp = "http/protobuf";
As we chatted about, I'll make the metrics updates in a separate PR! I'll add the JSON check to this PR

2022-09-28 16:16 UTC, MikeGoldsmith approved these changes
Looks great, thanks @pkanal 

I left one minor suggestion regarding local variable naming 😄

2022-09-28 16:16 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
> +            var _tracesEndpoint = options.GetTracesEndpoint();
nit: local variables don't need an _ prefix

2022-09-28 16:31 UTC, JamieDanielson approved these changes
![sometimes the right path is not the easiest one](https://user-images.githubusercontent.com/29520003/192835789-e47bc929-3a72-4654-8b5e-aefb693814ef.gif)

2022-09-28 17:56 UTC, merged