maint: Bump OpenTelemetry dependencies
honeycombio/honeycomb-opentelemetry-dotnet pull request #365
Opened 2024-02-26 12:50 UTC by MikeGoldsmith

## Which problem is this PR solving?
Bumps all OpenTelemetry dependencies across packages.

- Closes #364 

## Short description of the changes
- Bumps OTel dependencies to latest, in each package csproj

2024-02-26 13:51 UTC, TylerHelmuth requested changes
@MikeGoldsmith before we merge this I'd like to discuss the impact as these .NET versions bring along the HTTP semantic convention breaking changes.

2024-02-26 13:58 UTC, MikeGoldsmith commented
> @MikeGoldsmith before we merge this I'd like to discuss the impact as these .NET versions bring along the HTTP semantic convention breaking changes.

Ah, yes - looks like 1.6.0 of the instrumentation packages started updating semantic conventions. I was expecting a major version bump, not minor 😦

2024-02-26 16:52 UTC, cartermp commented
Yep, it's a true pleasure.

2024-02-26 19:57 UTC, MikeGoldsmith commented
@TylerHelmuth I've downgraded the instrumentation packages that use HTTP semantic conventions to [1.6.0-beta.3](https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/1.6.0-beta.3) and added a note to the README.

Let me know what you think

2024-02-27 13:24 UTC, TylerHelmuth commented on src/Honeycomb.OpenTelemetry.CommonInstrumentations/Honeycomb.OpenTelemetry.CommonInstrumentations.csproj
> +    <PackageReference Include="OpenTelemetry.Instrumentation.AspNet" Version="1.6.0-beta.2" />
Should this be .3?

2024-02-27 13:24 UTC, TylerHelmuth commented on src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
> +    <PackageReference Include="OpenTelemetry" Version="1.6.0" />
Is this the corresponding API version for the instrumentation version?

2024-02-27 13:33 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry.CommonInstrumentations/Honeycomb.OpenTelemetry.CommonInstrumentations.csproj
> +    <PackageReference Include="OpenTelemetry.Instrumentation.AspNet" Version="1.6.0-beta.2" />
There isn't a [beta.3](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNet) for plain AspNet so went with latest release before Nov 17

2024-02-27 13:35 UTC, MikeGoldsmith commented on src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
> +    <PackageReference Include="OpenTelemetry" Version="1.6.0" />
Yeah, [1.6.0](https://www.nuget.org/packages/OpenTelemetry) was the last stable release before Nov 17. There an alpha release between then and Nov 17, but preferred stable release.

2024-02-27 13:41 UTC, TylerHelmuth approved these changes

2024-02-27 13:48 UTC, merged